### ISSUE TITLE
Sign in error with "https://commentpara.de" as user

### ISSUE THREAD

**Issue by cweiske** [aaronpk/Teacup#3]
When trying to log in with `https://commentpara.de` as user, teacup shows an error:

> Unable to verify the sign-in attempt

The source of the problem might be that after signing in, the full user URL is returned (`https://commentpara.de/user/3.htm`) which is different from the original value (`https://commentpara.de`).

**Comment by aaronpk** [comment]
This is fixed in 7d00f3857c9a33888287adb69437c1df2d228ba0
